config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users
  resources :friends
  # get 'home/index'

  # root 'home#index'
  get 'home/about'
  root 'friends#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends

  has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
      @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Find correct user
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @text = "Hello from the HomeController.rb"
    @name = "Vuochlang Chang"
    @purpose = "Ruby on Rails Demo Project"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:task_name, :deadline, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name"%>
  </div>

  <div class="field mb-3">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name"%>
  </div>

  <div class="field mb-3">
    <%= form.text_field :email, class:"form-control", placeholder:"name@example.com"%>
  </div>

  <div class="field mb-3">
    <%= form.text_field :phone, class:"form-control", placeholder:"(111)-333-2222"%>
  </div>

  <div class="field mb-3">
    <%= form.text_field :twitter, class:"form-control", placeholder:"@twittername"%>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <!-- <% current_user.inspect%> -->
  <!-- <% current_user.id %> -->

  <br>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<br>
<%= render 'form', friend: @friend %>

<br>
<%= link_to 'Show', @friend, class:"btn btn-secondary"%>
<%= link_to 'Remove', @friend, method: :delete, data: { confirm: 'Are you sure?'}, class:"btn btn-outline-danger" %>
<%= link_to 'Back', friends_path, class:"btn btn-secondary"%>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <h1>Friends List</h1>

  <table class="table table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <!-- <th>User ID</th> -->
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
        <tr>
          <td>
            <%= link_to friend.first_name.capitalize() + " " + friend.last_name.capitalize(), friend , class:" text-decoration-none text-black" %>
          </td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <!-- <td><%= friend.user_id %></td> -->
          <!-- <td><%= link_to 'Edit', edit_friend_path(friend) %></td> -->
          <td><%= link_to 'Remove', friend, method: :delete, data: { confirm: 'Are you sure?'}, class:"text-decoration-none text-danger" %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>

<% else %>

  <div class="d-grid gap-2 col-6 mx-auto">
    <h1 class="text-center"> Welcome! </h1><br><br>

    <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-secondary" %><br>
    <%= link_to 'Sign In', new_user_session_path, class:"btn btn-outline-secondary" %>
  </div>

<% end %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>
<br>
<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Back', friends_path, class:"btn btn-secondary"%>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %>   &nbsp;|&nbsp;
    <%= @friend.phone %>   &nbsp;|&nbsp;  
    <%= @friend.twitter %>
    <br>
  </p>
  <hr class="my-4">
  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %>
  <%= link_to 'Remove', @friend, method: :delete, data: { confirm: 'Are you sure?'}, class:"btn btn-danger" %>
  <%= link_to 'Back', friends_path, class:"btn btn-secondary" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to 'Friend App', root_path, class:"navbar-brand"%>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "My Friends", friends_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "My Tasks", tasks_path, class:"nav-link"%>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
          </li>

        <% end %>

      </ul>
      <!-- <form class="d-flex"> -->
        <%= link_to "About Us |", home_about_path, class:"text-decoration-none text-secondary"%>
        &nbsp;&nbsp;&nbsp;
        <%= link_to "Edit Profile |", edit_user_registration_path, class:"text-decoration-none text-secondary"%>
        &nbsp;&nbsp;&nbsp;
        <%= link_to "Sign Out |", destroy_user_session_path, method: :delete, class:"text-decoration-none text-secondary"%>
      <!-- </form> -->
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<ul class="h3">
	<li><%= @name %></li>
	<li><%= @purpose %></li>
</ul>

app/views/home/index.html.erb
<h1>Hello World!</h1>
This is my first Rails Webpage....

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Friends App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render "home/header" %>

    <br>
    <div class="container">
      <% if notice %>
        <%= render "layouts/alerts"%>
      <% end %>

      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class="field mb-3">
    <%= form.label :task_name %>
    <%= form.text_field :task_name, class:"form-control", placeholder:"Task description" %>
  </div>

  <div class="field mb-3">
    <%= form.label :deadline %><br>
    <%= form.datetime_select :deadline%>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :task_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing "<%= @task.task_name.capitalize%>" </h1>

<%= render 'form', task: @task %>
<br>

<%= link_to 'Show', @task, class:"btn btn-secondary" %> 
<%= link_to 'Back', tasks_path, class:"btn btn-secondary" %>

app/views/tasks/index.html.erb
<h1 class="text-success">Current Tasks</h1>

 <table class="table table-bordered table-hover">
    <thead class="table-dark">
    <tr>
      <th>Task name</th>
      <th>Due Date</th>
      <th>Due Time</th>
      <th>Time Left</th>
      <th>User ID</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.user.id == current_user.id && (task.deadline.to_date - Date.today).to_i >= 0%>
        <tr>
          <td><%= link_to task.task_name.capitalize(), task, class:"text-reset text-decoration-none"%></td>
          <td><%= task.deadline.to_date %></td>
          <td><%= task.deadline.strftime("%I : %M %p") %></td>
          <td>
            <%= (task.deadline.to_date - Date.today).to_i%></td>
          <td><%= task.user.id %></td>

          <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class:"text-decoration-none text-danger"%>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path, class:"btn btn-secondary" %>

<hr>

<h1 class="text-danger">Past Tasks</h1>

<table class="table table-bordered table-hover text-center">
    <thead class="table-light">
    <tr>
      <th>Task name</th>
      <th>Due Date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.user.id == current_user.id && (task.deadline.to_date - Date.today).to_i < 0%>
        <tr>
          <td><%= link_to task.task_name.capitalize(), task, class:"text-reset text-decoration-none"%></td>
          <td><%= task.deadline.to_date %></td>

          <td><%= link_to 'Change Due Date', edit_task_path(task), class:"text-decoration-none text-primary"%>

          <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class:"text-decoration-none text-danger"%>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<br>
<%= link_to 'Back', tasks_path, class:"btn btn-secondary" %>

app/views/tasks/show.html.erb
<div class="jumbotron">
  <p class="display-4">
    <%= @task.task_name.capitalize %>
  </p>
  <% if @task.deadline.to_date == Date.today %>
    <p class="text-danger text-uppercase"> It is due today! </p>
  <% end %>
  <% if (@task.deadline.to_date - Date.today).to_i < 0 %>
    <p class="text-danger text-uppercase"> Task is overdue!! </p>
  <% else %>
    <p class="text-success text-uppercase">
      <%= (@task.deadline.to_date - Date.today).to_i %> days left to complete :)
    </p>
  <% end %>


  <p>
    <h4>Deadline:</h4>
    <strong>Date: </strong>  
    <%= @task.deadline.to_date %><br>
    <strong>Time: </strong>  
    <%= @task.deadline.strftime("%I : %M %p")%>
  </p>

  <hr class="my-4">

  <%= link_to 'Edit', edit_task_path(@task), class:"btn btn-secondary" %>
  <%= link_to 'Back', tasks_path, class:"btn btn-secondary" %> <br><br>
  <%= link_to 'Delete', @task, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %>
</div>